[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.coverage]
alias = "coverage-tarpaulin"

[tasks.coverage-tarpaulin.linux]
install_script = ["hash cargo-tarpaulin || RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo install --force cargo-tarpaulin"]
command = "rustup"
args = ["run", "cargo", "tarpaulin", "--out", "Xml"]
